Remove the requirement for 3 touch points
swri-robotics/toolpath_offline_planning pull request #16
Opened 2020-01-23 19:27 UTC by mpowelson

I'm not sure what the ultimate plan is for this (or any) feature. However, until the master plan for what this thing is supposed to look like is released, I'm proposing we remove the requirement to have 3 touch points.

2020-02-14 15:18 UTC, mpowelson commented
@DavidMerzJr @marip8 ping

2020-02-14 15:51 UTC, marip8 requested changes

2020-02-14 15:51 UTC, marip8 commented on opp_gui/src/widgets/tool_path_planner_widget.cpp
>          this, "Invalid Model Definition", "Ensure at least 3 touch points and 3 verification points have been defined");
I would also change this message to indicate the number of touch and verification points that are required

2020-02-14 16:01 UTC, marip8 commented
I created an issue #18 to discuss the fate of these features, but I think this is a good stop-gap measure for users who don't want/need to create the points

2020-02-14 16:10 UTC, marip8 approved these changes

2020-09-25 14:31 UTC, drchrislewis commented
@marip8 Who has authority to merge? I don't seem to. This one is long overdue for this simple fix.

2020-09-25 14:36 UTC, DavidMerzJr commented
@drchrislewis

@marip8 and @jrgnicho are (to my knowledge) the only ones who have merge rights on this repo.

2020-09-25 14:59 UTC, marip8 commented
It appears CI is failing because of a clang formatting issue. I'll update and merge today

2020-11-10 16:13 UTC, drchrislewis commented
@marip8 If you have permissions on this repo, please accept this PR. Also please give me permissions. I have several PR's between myself and Collin that we'd like to review and approve.

2020-11-10 16:48 UTC, merged